### PR TITLE
push the group-loader with 2 tags

### PR DESCRIPTION
**Pull request by choim-sci**
Hi @eahayes9, 

This PR is to push the image with2 tags, a custom tag and the short SHA. 
If you can review it, that will be great. Or let me know if you cannot. Thanks

### CODE REVIEW

**Review by eahayes9 — COMMENTED** [review]
Don't want the v1.0.0 tag.   We need to have a discussion with Cove whe he gets back about how are are going to do releases.  For now, you should only be pushing the tags with the SHA.

**Comment by choim-sci** [comment]
@eahayes9 
The one pushed out yesterday has the SHA tag.

**Comment by covesturtevant** [comment]
Agree with @eahayes9. The tag for modules should only include the short SHA. Same as what the build_tag_push_update.sh script does.

**Comment by choim-sci** [comment]
@eahayes9 and @covesturtevant , 

Don't short SHAs get expired in 30 days or so? I heard that the images with custom tags do not get expired.  And saw kafka-loader tagged with v3.2.1 in addition to the SHA.  We can discuss this later.

**Comment by covesturtevant** [comment]
Thanks @choim-sci. You're right. Steve J told me about this yesterday afternoon. Go ahead and continue your testing with the dual tags of  1) semantic versioning (e.g. v3.2.1) and 2) short SHA. We can discuss the semantic versioning plan in our meeting next week.

**Comment by choim-sci** [comment]
@covesturtevant and @eahayes9, 
 Sure.  We can iron out all the details during the meeting. In the meantime, the branch is renamed as choim-NSE9244-multi-tags, fyi.

**Pull request closed without merging**
