### PR TITLE
update for unit test

### PR DESCRIPTION
**Pull request by ncatolico**
@choim-sci

### CODE REVIEW

**Comment by choim-sci** [comment]
Hi @ncatolico, 

The reviewer was not assigned.  Let me know if you want me to review this PR.  I can certainly do that.

**Comment by ncatolico** [comment]
@choim-sci sorry about that. Yes, please review

**Comment by choim-sci** [comment]
@ncatolico and @covesturtevant, 

I approve the changes. But I do not seem to have the right to merge.

**Comment by covesturtevant** [comment]
@choim-sci You do have the right to merge. But you have to officially review and approve the PR first. Turning back over to you.

@ncatolico FYI

**Review by choim-sci — APPROVED** [review]
@ncatolico 

I approve

**Pull request merged**
