### PR TITLE
Choim nse10539 dev workflows

### PR DESCRIPTION
**Pull request by choim-sci**
@covesturtevant, 

1. all the CERT wfs are reverted and one DEV workflows, DEV-level1-pipeline-list only worked/tested. 
2. I will update the other 2 when Dawn approves. 

@ddlenz , 

3. inputs defined in the action 

4. the env vars set in the action from the inputs, 

5. the env var values passed into the action from your workflow using "with"

### CODE REVIEW

**Comment by choim-sci** [comment]
@covesturtevant 

#2 above, the other 2 DEV wfs, site-list and troll*, are updated/tested, fyi.

**Comment by ddlenz** [comment]
@choim-sci inputs look good - the action steps now need to set corresponding env vars for the python script to use

**Comment by choim-sci** [comment]
@ddlenz ,

Isn't the python script reading the env vars passed in from the workflows?

**Comment by ddlenz** [comment]
> @ddlenz ,
> 
> Isn't the python script reading the env vars passed in from the workflows?

No - they need to be set in the action from the inputs

**Comment by choim-sci** [comment]
> > @ddlenz ,
> > Isn't the python script reading the env vars passed in from the workflows?
> 
> No - they need to be set in the action from the inputs

Like this? 
      - name: install .....put_files/put_files.py
        shell: bash
        run: python3 -u .github/workflow_scripts/put_files/put_files.py ${{ inputs.pachd_address }} ${{ inputs.pach_token }} ${{ inputs.repo_name }} ${{ inputs.branch_name }} ${{ inputs.in_paths }}  ${{ inputs.out_paths }}

**Comment by choim-sci** [comment]
@ddlenz 

Or like this?

      - name: run .....put_files/put_files.py
        shell: bash
        env:
          pachd_address: ${{ inputs.PACHD_ADDRESS }}
          pach_token: ${{ inputs.PACH_TOKEN }}
          repo_name: ${{ inputs.REPO }}
          branch_name: ${{ inputs.BRANCH }}
          in_paths: ${{ inputs.IN_PATHS }}
          out_paths: ${{ inputs.OUT_PATHS }}_
        run: 
	  python3 -u .github/workflow_scripts/put_files/put_files.py

**Comment by ddlenz** [comment]
> @ddlenz
> 
> Or like this?
> 
> ```
>   - name: run .....put_files/put_files.py
>     shell: bash
>     env:
>       pachd_address: ${{ inputs.PACHD_ADDRESS }}
>       pach_token: ${{ inputs.PACH_TOKEN }}
>       repo_name: ${{ inputs.REPO }}
>       branch_name: ${{ inputs.BRANCH }}
>       in_paths: ${{ inputs.IN_PATHS }}
>       out_paths: ${{ inputs.OUT_PATHS }}_
>     run: 
>   python3 -u .github/workflow_scripts/put_files/put_files.py
> ```

Yes - like this, but uppercase - e.g. PACHD_ADDRESS

**Comment by choim-sci** [comment]
Hi @covesturtevant and @ddlenz, 

Dawn  wants to discuss a little more about the issue above. But she and I are out next sprint and I do not want the branch sitting stale. I will write a 1-point story for  the issue to track. So, do you guys mind closing this PR and merging the branch to master?

**Comment by choim-sci** [comment]
> Hi @covesturtevant and @ddlenz,
> 
> Dawn wants to discuss a little more about the issue above. But she and I are out next sprint and I do not want the branch sitting stale. I will write a 1-point story for the issue to track. So, do you guys mind closing this PR and merging the branch to master?

--- NSE-10576 is written for this.

**Review by covesturtevant — APPROVED** [review]

**Pull request merged**
