### PR TITLE
Choim nse9989 v3

### PR DESCRIPTION
**Pull request by choim-sci**
@covesturtevant, 

This PR is adding ERR_PATH as env. var. in pub_egress module and the test pipeline is testprod_pub_egress_and_publish.

### CODE REVIEW

**Comment by covesturtevant** [comment]
@choim-sci Let's chat about removing partial output for errored datums. I see output for the same datum in both the /errored_datums and successful output path.

**Comment by choim-sci** [comment]
@covesturtevant , 
I modified the basic/manifest.csv to error out.  So, files in basic should be in the error directory, expanded in the successful output directory. I used v2.0.2 to run.

**Review by covesturtevant — CHANGES_REQUESTED** [review]
@choim-sci Thanks, output looks great. One request before merging, can you please update the image version in all the relevant pipeline specs? When this gets pushed to master, a git action will update the parQuantumLine_pub_egress_and_publish pipeline in pachyderm-dev, so we can test the final integration.

**Comment by choim-sci** [comment]
@covesturtevant , 
Sure thing!  I will run the build script and let you know. Thanks

**Comment by choim-sci** [comment]
@covesturtevant, 

The version is updated for the yamls. Let me know if you want me to merge it to master.

**Review by covesturtevant — APPROVED** [review]
Beautiful, thanks @choim-sci!

**Pull request merged**
