### PR TITLE
Choim nse10538 pilot

### PR DESCRIPTION
**Pull request by choim-sci**
Hi @covesturtevant, 

This PR has action yml separated from the workflows file.  I named the branch *pilot as it has 2 workflows tried and tested. They are CERT-li191r-site-list.yml and CERT-level1-pipeline-list.
Let me know if this is what you expected or not.

### CODE REVIEW

**Comment by covesturtevant** [comment]
@choim-sci Looking good. Instead of the CERT workflows, could you please edit the DEV workflows? Then when we merge the PR into master we'll be able to test updates in pachy-dev. 

@ddlenz Mind taking a look?

**Comment by choim-sci** [comment]
@covesturtevant 

Sure, working on DEV workflows.

**Comment by ddlenz** [comment]
the action needs the env vars for the script
https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions#inputs

**Comment by covesturtevant** [comment]
@choim-sci Also, please revert edits to the CERT workflows until the DEV workflows test well.

**Comment by choim-sci** [comment]
@covesturtevant , will do

**Comment by choim-sci** [comment]
@ddlenz 
regarding the env vars, I do not see any params or arguments in the section calling put-files.py.  Do you have any specifics where env vars needed to be?

**Comment by ddlenz** [comment]
the env vars defined in the workflow (PACHD_ADDRESS, etc) are used by put_files.py
define inputs for those values in your action (read the link I sent above about github action inputs), set the env vars in the action from the inputs, and pass the env var values into the action from your workflow using "with"

**Comment by choim-sci** [comment]
@ddlenz ,

Alrighty, in-progress.

**Comment by choim-sci** [comment]
@covesturtevant  and @ddlenz ,

Removing the branch, choim-NSE10538-pilot and closing this PR.
Refer to a new branch, choim-NSE10539-DEV-workflows, and a new PR.

**Pull request closed without merging**
