### PR TITLE
NSE-6126 unit test added for json schema validation

### PR DESCRIPTION
**Pull request by choim-sci**
@covesturtevant , @visalachundru, @ilobopadilla ,

Below are the summary of the changes. 

1. 4 new files added: 
 - R/def.validate.json.schema.R
- tests/testthat/locations-emptyContents.json
- test/that/locations-invalidSchema.json
- test/that/locations-schema.json

2. 1 file removed: 
- test/that/test-base-function.R  

3. 3 files modified: 
- R/def.loc.filt.R 
- R/def.validate.json.R  --- this is for the coding consistency not the functionality
- test/that/test-loc-filt-function.R

### CODE REVIEW

**Comment by covesturtevant** [comment]
@choim-sci Thanks. Looking good. A couple questions for in-person follow-up:

- When a bad json is sent to def.loc.filt and thus identified by def.validate.json, what is returned by def.loc.filt? I would expect an error status to be returned - i.e. one that can be caught with tryCatch. Is this the case? I'm not familiar with the use of on.exit() in combination with log$error, so it's not clear to me whether this is indeed the behavior.

- I've been using (and adding to) your function def.validate.df and def.validate.vector.notEmpty. These are very useful. I wonder if it is best to do the logging of errors within these functions so that they don't need to clutter up the functions that call them. What do you think? This would also apply to def.validate.json.

**Comment by choim-sci** [comment]
@covesturtevant,

- When an input json fails validation, validate.json and validate.json.schema, the main body of def.loc.filt will not run.  So, there will be no output json. I can use tryCatch with error message. If I remember correctly, in R once a fn erred out, the unit test stopped running.  

- I will try logging the error msg on those functions.  I have been pondering this whether to add or not.  

Thanks for the good feedback, I appreciate you!!

**Comment by covesturtevant** [comment]
@choim-sci 

Thanks, and I appreciate you too!

Can you look into getting def.loc.filt to return error status when the validations fail? We will need to catch error status from def.loc.filt with tryCatch (or similar) in order to correctly implement error handling. My concern with the function simply returning no output is that the main code does not know that it failed (other than the logs) and will continue to run and error somewhere else when it does not have what it needs.

**Comment by covesturtevant** [comment]
@choim-sci Oh, and great to hear you agree on adding logging to the validation functions. You can skip def.validate.df and def.validate.vector.notEmpty, as I am working with these currently and will add the logging.

**Comment by choim-sci** [comment]
@covesturtevant,

Back to your question regarding a bad json, there are 2 scenarios to consider: 
- on Error,  tryCatch will catch the error, i.e., a wrong json file is passed on, etc.. 
- not Error, but FAIL (the validation,) what would you expect to happen?

**Comment by choim-sci** [comment]
@Frencil Hey Chris, 

Thank you for the feedback.  I will review them one by one, there are a lot!!

**Comment by choim-sci** [comment]
Closing this, opening a new PR on a new branch.

**Pull request closed without merging**
