### PR TITLE
Pachy ptb330a choim

### PR DESCRIPTION
**Pull request by choim-sci**
Hi @covesturtevant 

Let me know if I can merge these ptb330a jsons to master.  Thanks

### CODE REVIEW

**Comment by covesturtevant** [comment]
@choim-sci Looks like the calibration conversion module needs some edits. The term looks incorrect (resistance).

**Comment by choim-sci** [comment]
@covesturtevant, ptb330a_calibration_conversion.json?

**Comment by covesturtevant** [comment]
@choim-sci yes

**Comment by covesturtevant** [comment]
@choim-sci Good fix on the calibration conversion module. Everything looks good until the context filter. This pipeline doesn't need a context filter. It will eventually use a related location grouper, but the other products to group aren't ready yet. Go ahead and delete the context filter, skip the related location grouper (for now), and connect downstream pipelines to your named location filter.

**Comment by covesturtevant** [comment]
@choim-sci it's the context filter you want to remove, not the calibration filter

**Comment by choim-sci** [comment]
I know,
I am in the process of recovering the files I accidently removed and commented wrong.

**Comment by covesturtevant** [comment]
Looks good, @choim-sci! Feel free to merge to master and start a new dev branch.

**Pull request merged**
