### PR TITLE
Choim nse9808 v2

### PR DESCRIPTION
**Pull request by choim-sci**
@covesturtevant , 

This PR is for pub_packager update for the unit test and pub_packager.py. 

The change in pub_packager.py is to resolve n error below, 

    " manifest_hasData = pd.read_csv(manifest_file, header=0, squeeze=True, index_col=0,usecols=['file','hasData']).to_dict()
     TypeError: read_csv() got an unexpected keyword argument 'squeeze'"

And the unit test is updated with minor changes.

### CODE REVIEW

**Comment by covesturtevant** [comment]
Thanks @choim-sci. Has the change to "squeeze" been tested to result in identical output?

**Comment by choim-sci** [comment]
@covesturtevant , 

See if the test data is "small" enough.

**Comment by choim-sci** [comment]
@covesturtevant, 

pub_packager requirements.txt has pandas==1.2.5.

The parameter squeeze is DEPRECATED since pandas version 1.4.0. The details in the link, 

https://stackoverflow.com/questions/62982500/when-i-read-a-csv-with-squeeze-is-set-to-true-in-pandas-it-makes-dataframe-not-s

I have 2.0.3 installed in PyCharm and saw the error. 
I ran with the change and w/o it and saw the same results.

**Comment by covesturtevant** [comment]
@choim-sci Thanks, love the beautifully small test dataset. 

Can you try running the unit test on den-devissom-1? It fails when I download your branch and run it there.

**Comment by choim-sci** [comment]
@covesturtevant, 

Was the failure like this, "PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: '? 

Looks like os.chdir(self.output_path) make the temp directory stay open. 

I added a line to close it.  If the error you saw is the one above, please pull and run again.

**Comment by covesturtevant** [comment]
This is the error I'm getting:

**Comment by choim-sci** [comment]
@covesturtevant, 

Hmmmm, I do not get that error.  

Can you copy test_pub_packager.py you have and send it to me?  Let me try it to see if I get the same.

**Comment by choim-sci** [comment]
@covesturtevant, 

The fix is checked in,  works on both, Windows and Linux.

**Comment by covesturtevant** [comment]
Excellent. Thanks @choim-sci

**Pull request merged**
