### PR TITLE
Visala unit testing

### PR DESCRIPTION
**Pull request by visalachundru**
Please review the test cases that I had written for testing the Calibration filter and provide me your feedback.

### CODE REVIEW

**Comment by covesturtevant** [comment]
@visalachundru Thanks. A few edits to start:

- This pull request should be made to a branch other than master. We are not yet ready to make changes to how the workflows are called (i.e. turning them into functions). I recommend making a new branch called something like "functionalize.workflows" to issue pull requests into. That way you can continue your development of test cases for entire modules, and we can integrate that work into master after full testing.
- We need to limit the size of test files to the minimum necessary for the test cases, so that the size of this repository remains small. This can be accomplished by stripping out calibration information that is not used by the workflow (we can always add more later if other tests need it). Smaller avro files can be created by 1) opening a file using NEONprocIS.base::def.read.avro.deve, 2) removing most rows in the data frame (leave maybe 5 rows), and 3) resaving the file using NEONprocIS.base::def.wrte.avro.deve. When you have a smaller set of test data, please create a clean development branch from master and add the new files and other edits you've made to code (completely excluding the data files in this pull request so they are not in the commit history). 

Please make these edits and resubmit the pull request.

**Comment by choim-sci** [comment]
@visalachundru, My comments are about the R test directory/structure for the test files . 
The R test files live in tests/testthat.
This command,  usethis::use_testthat(), will create tests/testthat directory and a file tests/testthat.R 
One of your test files, NEON-IS-data-processing/flow/flow.cal.conv/flow.cal.conv.test.R, should be in NEON-IS-data-processing/flow/flow.cal.conv/tests/testthat/flow.cal.conv.test.R.  This way R will run all the tests under flow.cal.conv by the command, "devtools::test(pkg="......../NEON-IS-data-processing/flow/flow.cal.conv"   The same applies to flow.cal.filt.  Thanks!

**Comment by covesturtevant** [comment]
@visalachundru I took a look at the test cases. Most look great. Some adjustments:

It is possible that no calibration file will be found in the output if no calibration file had a valid date range on or prior to the data date. This would occur if the first calibration was valid only after the data date. In this case, a warning is issued (line 159 of your edited version of flow.cal.filt.R). Can we add another test for this and modify the first test (cal file in the output) to pass only if no warnings or errors are issued?

**Comment by covesturtevant** [comment]
@visalachundru closing this pull request to reset for next time there is something to review.

**Pull request closed without merging**
