### PR TITLE
removed browser and more documentation

### PR DESCRIPTION
**Pull request by rhlee12**

### CODE REVIEW

**Comment by rhlee12** [comment]
@covesturtevant just mopping up that browser

**Comment by covesturtevant** [comment]
Thanks @rhlee12!

One request: can you please clean up your pipeline specs, removing all unused specs (json versions as well as e.g. parQuantumLine_statistics_uncertainty_group.yaml)

**Comment by rhlee12** [comment]
Done, think I got all of the unused specs

**Comment by covesturtevant** [comment]
Beautiful. Thanks @rhlee12!

**Pull request merged**
