### PR TITLE
Choim nse6057

### PR DESCRIPTION
**Pull request by choim-sci**

### CODE REVIEW

**Comment by choim-sci** [comment]
Closed the previous PR, #2, and opened a new one.

**Comment by covesturtevant** [comment]
@choim-sci A couple edits please:

- can you strip out most of the content of the json files so they are the minimum necessary to demonstrate pass/fail of the tests? 
- The log object should be passed into the function and only created if it is null. Please also make this edit to the function(s) in the previous merge.

Thanks!

**Comment by choim-sci** [comment]
Hi @covesturtevant, I CAN: 
   - strip more from locations-invalid.json; 
   - remove locations-output.json after the test is done,
CANNOT (due to lack of the knowledge, i.e., what is required for the valid testing): 
   - strip any from locations.json.  If you can provide the info of the removable fields, I can.

**Comment by choim-sci** [comment]
Closing this PR, #4.  Please review a new PR, #5, instead.

**Pull request closed without merging**
