### PR TITLE
Choim nse8879

### PR DESCRIPTION
**Pull request by choim-sci**
Hi @covesturtevant, 

R set up is added to run the R script of updating the pipeline spec yamls.

### CODE REVIEW

**Review by covesturtevant — DISMISSED** [review]

**Review by choim-sci — COMMENTED** [review]
Reviewed with Cove.

**Review by choim-sci — COMMENTED** [review]
.github/workflows/build-and-push directory is replaced with .github/workflows/build-push-updated

**Review by choim-sci — COMMENTED** [review]
Reviewed

**Comment by choim-sci** [comment]
Hi @covesturtevant , 

Your approval seemed to get stale after I renamed the directory, build-and-push, as build-push-update.  When you have time, please approve it again or merge the branch to master.

**Review by covesturtevant — APPROVED** [review]
Looks good so far. Reminder that we still want the action to create a PR back to master with the pipeline update commit

**Pull request merged**
