### PR TITLE
Choim inst extdata

### PR DESCRIPTION
**Pull request by choim-sci**
@covesturtevant, 

Here it is.  This PR has:  
- Remove tests/testthat/locations-schema.json 
- Add inst/extdata/locations-schema.json to NEONprocIS.base pkg
- Remove tests/testthat/calibration.xsd 
- Add inst/extdata/calibration.xsd to NEONprocIS.cal pkg
- the changes made due to these added files.

### CODE REVIEW

**Comment by eahayes9** [comment]
Mija,

Are you using  https rather than ssh to clone, etc the github.com/NEONScience/NEON-IS-data-processing.git?

To tell run the command:

git remote –v

I am looking at the git help credentials man page to see how to fix this problem.  It would not happen if you used ssh rather than https.

Give me a fe minutes.

Liz
---
Elizabeth Hayes
SCM Engineer
National Ecological Observatory Network (NEON) Program
Office: 720.330-1593
lhayes@battelleecology.org<mailto:lhayes@battelleecology.org>
hayese@battelle.org<mailto:hayese@battelle.org>

Battelle
1685 38th Street
Boulder, CO 80301
http://www.battelle.org/neon

**Comment by covesturtevant** [comment]
Hi @choim-sci, I'm getting an error trying to run a location from the pipeline through def.validate.json.schema. Can you please check out this error? I'll email you the json file shortly.

`NEONprocIS.base::def.validate.json.schema (NameFileIn, locJsonSchema)

WARN  [2020-03-31 08:53:21.915] /scratch/pfs/exofdom_calibrated_location_group/exofdom/2019/01/01/21310/location/exofdom_21310_locations.json does not conform to the schema  

Warning messages:
1: In readLines(x) :
  incomplete final line found on '/scratch/pfs/exofdom_calibrated_location_group/exofdom/2019/01/01/21310/location/exofdom_21310_locations.json'
2: In readLines(x) :
  incomplete final line found on '/scratch/pfs/exofdom_calibrated_location_group/exofdom/2019/01/01/21310/location/exofdom_21310_locations.json'`

**Comment by covesturtevant** [comment]
Sorry, didn't realize I closed it.

**Comment by choim-sci** [comment]
@covesturtevant , 

locations-schema.json is updated (in synch with the one in the master) after the two fields removed from the required. 
Thanks !

**Comment by choim-sci** [comment]
@covesturtevant ,

calibration.xsd is updated, tested and pushed up in both branches, master and choim-inst-extdata, for your review.

**Comment by choim-sci** [comment]
@covesturtevant , 

The changes were made in calibration.xsd following the highlighted except "NEONPN." 
I made it optional due to the error (some calibration xmls did not have this. )

**Pull request merged**
