### PR TITLE
Choim logjam loader

### PR DESCRIPTION
**Pull request by choim-sci**
@covesturtevant, 

This has 2 modules, path_order and logjam_loader. Thanks.

### CODE REVIEW

**Review by covesturtevant — CHANGES_REQUESTED** [review]
Looks good except that there are 4 pipeline specs that reference the logjam_loader image. Example: `/pipe/troll/troll_logjam_list_files.yaml`
I can also see one pipeline spec for path_order that needs the updated image: `/pipe/sandbox/calibration_path_reorder.json`

**Comment by choim-sci** [comment]
@covesturtevant, 

Ok, I can add troll_logjam_list_files.yaml.  calibration_path_reorder.json is on sandbox.  Do you want it to be added too?  I guess, it can serve as template.

**Comment by covesturtevant** [comment]
Yes, please. When moving these images to the GCP registry, please search and replace all pipeline specs that reference the old quay.io image.

**Review by covesturtevant — APPROVED** [review]
Looks great. Thanks.

**Pull request merged**
